### ISSUE TITLE
Ctrl-R is broken

### ISSUE THREAD

**Issue by jenspinney** [XanderStrike/devenv#6]
I don't know what is causing this, but anyone trying `Ctrl-R` gets this error:

```
Command 'fzf' not found, but can be installed with:    

apt install fzf
```

**Comment by XanderStrike** [comment]
@christianang It looks like you have made commits related to this recently, ok if i assign you?

**Comment by christianang** [comment]
Yeah that is fixed: https://github.com/cf-routing/devenv/commit/d259c652a85b52da179fca600d9b02783b8f5845
